# Use Node.js LTS version
FROM node:20

# Set the working directory
WORKDIR /recoleta-news

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the frontend
RUN npm run build

# Expose the port used by the frontend
EXPOSE 3000

# Command to start the application
CMD ["npm", "start"]
